#!/bin/bash
#
# Setup: clone wireless-testing and wireless-regdb git trees under
#        the paths pointed to by below env vars
#
KERNEL_DIR=${KERNEL_DIR:-~/ext/wireless-testing}
WIRELESS_REGDB_DIR=${WIRELESS_REGDB_DIR:-~/ext/wireless-regdb}
HERE=$(/bin/pwd)

set -e

mkdir -p rootfs

truncate -s 512M rootfs.img
sudo mkfs.ext4 rootfs.img
sudo mount -t ext4 rootfs.img -o loop rootfs

# install base debian
sudo debootstrap --arch=amd64 stable rootfs http://ftp.us.debian.org/debian/ ||:

# set up mounts used by VM tests
sudo mkdir -p rootfs/local

cat<<_EOM | sudo tee rootfs/etc/fstab
proc	/proc	proc	defaults	0	0
/dev/vda  / ext4  defaults   0   0
/dev/local    /local    9p    trans=virtio,version=9p2000.L   0   0
_EOM

echo "vm" | sudo tee rootfs/etc/hostname
cat<<_EOM | sudo tee rootfs/etc/hosts
127.0.0.1	localhost vm

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
_EOM

# install kernel modules
cp config-vm $KERNEL_DIR/.config
pushd $KERNEL_DIR
make -j8
sudo make modules_install INSTALL_MOD_PATH=$HERE/rootfs
cp arch/x86_64/boot/bzImage $HERE/testing-vm-kernel
popd

# install own init
sudo cp init.sh rootfs/sbin
pushd rootfs/sbin
sudo rm init
sudo ln -s /sbin/init.sh init
popd

# install wireless regdb
sudo mkdir -p rootfs/lib/firmware
sudo cp ${WIRELESS_REGDB_DIR}/regulatory.* rootfs/lib/firmware/

# install iw
sudo mount -t proc none rootfs/proc
sudo mount --bind /sys rootfs/sys
sudo mount --bind /dev rootfs/dev
sudo cp /etc/resolv.conf rootfs/resolv.conf
sudo chroot rootfs apt-get -y install iw sudo rfkill \
    libconfig-dev procps psmisc
sudo chroot rootfs apt-get clean

sudo umount -R rootfs

mv rootfs.img testing-vm-rootfs.img
sudo zerofree testing-vm-rootfs.img
xz testing-vm-rootfs.img
